### ISSUE TITLE
vagrant up /host_name_regex_pattern/ errors out

### ISSUE THREAD

**Issue by aswadrangnekar** [fabriziopandini/vagrant-compose#3]
vagrant supports using host regex patterns to bring up multiple nodes.
After installing this plugin it started giving errors.

It will be helpful if the plugin provides support for vagrant 

```
- vagrant up <node_group_name>
and
- vagrant up <cluster_group_name>
```

**Comment by fabriziopandini** [comment]
Now vagrant up and vagrant provision support also a list of machine name /  regular expressions.

Unfortunately suggested filters (cluster name and node group name) can't be supported because vagrant complains "The machine with the name '...' was not found configured for this Vagrant environment."

**Comment by aswadrangnekar** [comment]
Thanks for a quick turn-around and for this plugin!
:)
