### ISSUE TITLE
'hostmanager' "real" ip address

### ISSUE THREAD

**Issue by fabriziopandini** [fabriziopandini/vagrant-compose#7]
from [v1k0d3n](https://github.com/v1k0d3n) - issue [#6](https://github.com/fabriziopandini/vagrant-compose/issues/6)

you don't happen to know how i can write the 'hostmanager' "real" ip address to the inventory file, rather than the NAT port redirect, do you? that's my next problem...and i have no clue where to go.

**Comment by v1k0d3n** [comment]
sorry to brig up two questions in a single issue. trying to work through this issue, but cannot find a way to do this (maybe i just don't have enough knowledge).

**Comment by fabriziopandini** [comment]
Don't worry.
The question is not fully clear to me. What do you mean with 'hostmanager' "real" ip? What are you trying to achieve?

My guessing is that you are trying to make nodes in a cluster talk each other or setting some software for doing this (kuernates? flannel?), but I'm not sure...

**Comment by v1k0d3n** [comment]
yes, that's right. what happens is the inventory creates groups fine (that that i understand this better), however the inventory contains the localhost/port address to contact the nodes, which causes issues when using the ansible provisioner.

**Comment by v1k0d3n** [comment]
it's like i'm so close with this project...yet can't figure it out (it's the last hurdle). once i'm done, i'll have a really nice portable vagrant development wrapper around the kubespray/kargo project (used as a git submodles).

**Comment by fabriziopandini** [comment]
Ok let's start by sharing some background info/common practices that I use when building my cluster:
- by default each node is assigned an unique ip by vagrant-compose "172.31.#{group_index}.#{100 + node_index + 1}" (you can override this). 
- when provisioning the cluster you can use this ip to setup a [private network](https://www.vagrantup.com/docs/networking/private_network.html) like in this [example](https://github.com/fabriziopandini/vagrant-compose#creating-nodes). 
- if you setup a private network, vagrant boxes will get an additional network card with the above ip
- by using vagrant-host manager, /etc/host in each vagrant box (and eventually also in your host system) wiil be change allowing to resolve machine fqdn to the above ip
- by defining ansible_host_vars/ansible_group_vars with assigned the ip or the fqdn, I can configure ansible provisioning to properly update configuration files within the vagrant boxes
- sometimes, it is necessary to configure software in order to use the network card created for the network card (eth1) instead of the default network card.
- vagrant-compose has no notion of ports

**Comment by v1k0d3n** [comment]
i *think i'm doing things correctly, but maybe missing something? i posted by config/vagrantfile up: https://github.com/v1k0d3n/vagrant-kargo-kubernetes/tree/master/vagrant

to your points, i used your example as a baseline (you'll see a lot of similarities) thinking that would work mostly as expected.

**Comment by fabriziopandini** [comment]
no news since long times... if the project is still there, please let me know
