### ISSUE TITLE
Create group_vars and host_vars directory only if necessary

### ISSUE THREAD

**Issue by fabriziopandini** [fabriziopandini/vagrant-compose#9]
Create host vars and host_vars are created even if no file will be generated inside.
Expected behavior:
 - if dir exist, clean up
 - if a file should be written create directory if not exists

**Comment by davidmnoriega** [comment]
Is this related to `provisioning/host_vars` and `provisioning/group_vars` being created, even though I'm not using any ansible provisioners? I just noticed this when starting a new project, and not sure if I want to add it to my gitignore

**Comment by fabriziopandini** [comment]
yes, it is related.
Now, with this enhancement, provisioning/host_vars and provisioning/group_vars folders will be created only if necessary
